### ISSUE TITLE
Create new extension !

### ISSUE THREAD

**Issue by jigarmistry** [gi0baro/weppy#124]
First of all congratulations for great work ! (creation of weppy) 👍  . I really like this framework. It is best for my purpose.
 
I need to create new extension for my purpose . How can I get started ?  Is there any docs ? (I have not find in official documentation).

**Comment by gi0baro** [comment]
Thank you @jigarmistry, I'm glad you like the project.

Regarding your question, I'm sorry but I haven't written that part of the documentation yet.
I will try to explain you how them works, but first of all I will need to know if your extension will be related to templates or not, because they are quite different from the *standard* ones.

**Comment by jigarmistry** [comment]
Thanks for reply.

I am going to build GUI tool for my website(something like admin).  So I think it is not related to templates. I just need to understand the extension creation for weppy.

**Comment by gi0baro** [comment]
Ok. An extension it's a very simple class as you can see from the source code of the class: https://github.com/gi0baro/weppy/blob/master/weppy/extensions.py#L15L30

What you have to do is override the `on_load` method (don't override the init unless you **really** know what you're doing) and you have access to the `app`, `config` and `env` variable on the extension instance. These variables are initialised by weppy when the user write down `app.use_extension(YourExtensionClass)`.

Typically weppy auto-configure the namespace with the name of your extension, so if your extension class is named `FooBar`, then the config is initialised under `app.config.FooBar`.
Both `config` and `env` are weppy's `sdict` objects (basically dictionaries where you can get and set items as attributes), and you can typically do whatever you want with the `app` variable which is the application object itself.

You can also define routes for the user since you have the application instance:

```python
from weppy.extensions import Extension

def my_route_method():
    # some code

class MyExtension(Extension):
    def on_load(self):
        self.app.route('/somepath')(my_route_method)
```

Also mind that the source code now is for the current master, which introduced the `default_config` attribute on the `Extension` class, but in weppy 0.6.x (current release) this is not available, so if you want to add a default config you should write the load yourself.

If you have any additional questions, I will be happy to answer. You may also find useful take a look at some existing extension like https://github.com/gi0baro/weppy-sentry/blob/master/weppy_sentry/ext.py

**Comment by jigarmistry** [comment]
Thanks for great explanation !...
Now I have a clear picture of extension chemistry ! :)

**Comment by gi0baro** [comment]
I'm closing this since I opened #129
