### ISSUE TITLE
Production Ready?

### ISSUE THREAD

**Issue by shakna-israel** [gi0baro/weppy#13]
How far away is this project from being able to be run in the wild?

**Comment by gi0baro** [comment]
Hi @shakna-israel, actually there are no real "limitations" in running weppy on a production environment, I'm using it on some projects right now. The main deal here is that right now is developed just by me and since it's not largely used the bug fixing can be quite slow.
Anyway, if you're interested into using weppy for your projects, I suggest you to wait the **0.2** release (which should be available in the next week) since it will be the 'first public beta release' and introduces some major changes in the APIs. With 0.2 I will update the documentation also for the production environment, and I don't expect to see large bugs into the 'main' code.
At this point, I only expect to see some minor bugs on the `Auth` module available under `weppy.tools` but if so, with a bit of testing they will disappear shortly in the next release.

**Comment by shakna-israel** [comment]
Awesome.
