### ISSUE TITLE
is there a way to change form content before save to db?

### ISSUE THREAD

**Issue by saggit** [gi0baro/weppy#142]
I use the build in form, what can i do after form.accepted?

thanks

**Comment by gi0baro** [comment]
Hi @saggit,
actually the only way to hook into form validation is the `onvalidation` option, see docs: http://weppy.org/docs/0.7/forms#custom-validation

Actually, since your method is invoked after the model validation, and before the acceptation, you can use this method also to override or manually write values for the form:

```python
@app.route("/myform")
def myform():
    def process_form(form):
        # change a value
        form.params.number =  42

    form = YourModel.form(onvalidation=process_form)
    if form.accepted:
        # the value 42 was inserted/updated
    return dict(form=form)
```

If you have any further questions feel free to ask!

**Comment by saggit** [comment]
Hi,  @gi0baro 

Thank you for your explanation and the example, One more question, How can I unescape the html text in template? I already try to use `{{=html.unescape(html_text)}}`

**Comment by gi0baro** [comment]
@saggit if you mean that you already have an html string and you want to avoid the templating system to escape it, you can use the `asis` helper (http://weppy.org/docs/0.7/templates#basic-context):

```html
<div>
{{=asis(mycomponent)}}
</div>
```

If you really need to unescape, meaning converting an html escaped string to an unescaped one, you will need to do that in the python code of your application using the standard library.

Note that, it's not documented yet, but you can use the `tags` module of weppy to generate html content from python:

```python
from weppy.tags import tag

myh1 = tag.h1("this is H1", _class="somecssclass")
```

and just put it into the template.

**Comment by saggit** [comment]
@gi0baro  Thanks for help, very useful.
