### ISSUE TITLE
Template support in .js files

### ISSUE THREAD

**Issue by josejachuf** [gi0baro/weppy#169]
@gi0baro You can add the same template support in .js files

**Comment by gi0baro** [comment]
@josejachuf this is not so simple.
And, I'm probably missing the point. What's the use case for this? Or, in other words, what's the point of having a dynamic language nested into another dynamic language (javascript)?

**Comment by josejachuf** [comment]
@gi0baro I give you a concrete example. I have an html that I added a lot of js. What I want to do is move the javascript code to a js file. The problem is that I use the "url" function of weppy within the javascript.
I know I can solve it differently.

**Comment by mijdavis2** [comment]
If you really want to get that url generated from the rendered weppy template, one workaround might be to query the DOM in your js and get the URL from a web element or based on web element/event.

**Comment by gi0baro** [comment]
Ok, here is what I think:

- I see a very limited use case for this
- The ability to use python inside javascript is more risky than useful
- js files are intended to be *static*, so by definition is a counter-sense to have them dynamically re-parsed and written on every request (and is also a performance kill operation)

@josejachuf for the *url* use-case you provided I would reply with two possible answers:
1) if you need to add just a few routes, then you can statically type them in the template, since javascript scope is always global you can access them in other scripts, eg:

```html
<script type="text/javascript>
var myroute = "{{=url("route")}}";
</script>
```

2) if you need to do weppy routing with javascript, then probably is not the better use of weppy itself. I mean, if you really want something very dynamic, you should use a client-side framework, there are plenty of them to pick. The best you can do to make the frontend dynamic with weppy is to use a lot of ajax logics, but in this case, is really dependant on what you want to build in order to give good advices.

**Comment by josejachuf** [comment]
Ok. I agree with the comments. I think we should close this isssue
