### ISSUE TITLE
two advice for `url`

### ISSUE THREAD

**Issue by alingse** [gi0baro/weppy#173]
given

```python
@app.route(['/api/v1/book/isbn/<str:isbn>', '/api/v1/book/<int:bookid>'])
@service.json
def book(isbn=None,bookid=None):
    # code
```

###  1.  may `url` use a specific index param?

like this :
```python
url('book',  234)
'/api/v1/book/isbn/234'
url('book',  123, index=1)
'/api/v1/book/123'
```
with default index is 0
```
def url(path, args=[], index=0):
     pass
```
this is much better than format string `“book_1”`

this way may also nice for `_routes_str ` OrderDict,  

use `(name, index)` as the key like this ： `_routes_str[(name, index)]=Route `

can avoid the  name conflict.

```python
@app.route(paths)
def book():
    pass

@app.route(path)
def book_1():
    pass
```

###  2. should `url` support named params ?

```python
url('book', bookid=33333)
'/api/v1/book/33333'
url('book', isbn=33333)
'/api/v1/book/isbn/33333'
```
this might be difficult or meaningless

**Comment by gi0baro** [comment]
1) that can be hard for the routing itself. `_routes_str` is used just by the routes command via shell. I can change the notation from `"book_1"` to `"book.1"` since you can't have dots in routes (are used by the modules) and this should avoid conflicts.

2) `url` might support named params, but won't be capable to understand which route you want to use (I just can't imagine an efficient algorithm to do that on runtime). So yes, I might allow the usage of both a list or a dictionary for route variables but it won't help your need :)

**Comment by gi0baro** [comment]
@alingse with a494cba I've changed the format from `"book_1"` to `"book.1"`

**Comment by alingse** [comment]
ok, thank you @gi0baro
