### ISSUE TITLE
Create a form . Full example ?

### ISSUE THREAD

**Issue by ramstein74** [gi0baro/weppy#52]
my code to create a form does not work
```
from weppy import App
from weppy import Field, Form
from weppy.validators import inSet

app = App(__name__)
@app.expose('/form')
def a():
    simple_form = Form({
        'name': Field(),
        'number': Field('int'),
        'type': Field(
            validation={'in': ['type1', 'type2']}
        )
    })
    if simple_form.accepted:
        pass
    return dict(form=simple_form)
@app.expose("/")
def hello():
    return "Hello world!"

if __name__ == "__main__":
    app.run()

```

i get this error

Traceback (most recent call last):
  File "C:\weppy1.py", line 12, in a
    validation={'in': ['type1', 'type2']}
AttributeError: 'NoneType' object has no attribute '_csrf_tokens'

**Comment by gi0baro** [comment]
Hi @ramstein74,
you need a session handler in order to get forms work. The idea behind the quickstart is that you follow the entire flow (sessions are just before the forms section).

Moreover, if you want a full example, you should check out the [tutorial](http://weppy.org/docs/0.5/tutorial) that helps you building a complete application.

Please, next time you need support, use the [weppy talk group](https://groups.google.com/forum/#!forum/weppy-talk), since issues on github should be used for bug or feature requests.
