### ISSUE TITLE
Add requirements and performance data

### ISSUE THREAD

**Issue by GiantCrocodile** [gi0baro/weppy#56]
It would be helpful for making a decision to use whether weppy or not to see server and python requirements of weppy like dependencies, RAM and CPU usage and some performance data like how many requests weppy can process without struggling.

**Comment by gi0baro** [comment]
@GiantCrocodile weppy doesn't have any *strict* requirements about the hardware of the machine used; the only requirement is the python version you're using.
In fact, the RAM and CPU usage depends more on you're application code rather than the framework itself (and this is true with any web framework you're using); it would be quite hard supposing the RAM usage of weppy without any information about the specific application.

The only benchmarks I've seen including weppy are available at http://klen.github.io/py-frameworks-bench, they should give you an idea on how it performs in terms of requests per second compared to other frameworks.

As soon as I'll see more benchmarks involving weppy I'll populate a page on the main website.
At the moment, this is all I've got :)
