### ISSUE TITLE
Improve internationalization: add Auth strings (user, pw, email, ...) to Translation by default

### ISSUE THREAD

**Issue by GiantCrocodile** [gi0baro/weppy#69]
It would be nice for internationalization if Weppy's strings are translateable by default.

This would cover the following functions:
- registration
- forgot password, email
- log in
- profile

**Comment by gi0baro** [comment]
Would be nice, but I have 2 issues with that:

- The translations of the auth should be included in the app's translations files, but weppy doesn't provide any scaffold app, so how should I add these translations to the apps?
- Even if I figure out how to solve the first point, since auth is in the `tools` package and is not necessary in weppy (you can build an app without auth module), is it correct to add useless translations to your app anyway? I don't think so..

**Comment by GiantCrocodile** [comment]
I'm not sure if I did understand your first point correctly but what I thought about is that the developer adds the language files himself - they won't be provided by default by Weppy. You just add `T(...)` to the strings so if someone uses this module he/she can simply define them in the language file and it is done, without self-modifying weppy auth module files.

So you don't need to add all these translations nor it would change the sourcecode for someone if they do not use the module at all.

**Comment by gi0baro** [comment]
@GiantCrocodile LoL, you're probably right. Will dig a bit into the code and trying to add this.
