### ISSUE TITLE
Auth: True for read is ignored on form_profile_rw

### ISSUE THREAD

**Issue by GiantCrocodile** [gi0baro/weppy#76]
When I set `form_profile_rw` for field `username` to `(True, False)` in my `User(AuthUserBasic)` model the username field isn't displayed. It looks like read-access is broken and only writing works because if I set it to `(True, True)` or `(False, True)` I can see a textfield to type in.

Expected behaviour is explained here: http://weppy.org/docs/0.5/dal#the-models-setup-helper

**Comment by gi0baro** [comment]
@GiantCrocodile yes I know, this is a missing feature.
Right now weppy forms shows up only writable fields, since there's no logic for handling readable-only fields in the code, no matter if a standard form, or an auth profile or registration form. I'll try to put this on the next milestone.

**Comment by gi0baro** [comment]
@GiantCrocodile I'm sorry about that, but I'm gonna re-schedule this for 0.7
I want to release the new version in the next week, and right now I'm very busy on writing documentation for the long list of changes of 0.6 and finalizing some new features.

**Comment by GiantCrocodile** [comment]
This is okay @gi0baro. I appreciate your hard work and I hope you had a very nice christmas and new year eve!

**Comment by gi0baro** [comment]
@GiantCrocodile thanks, I hope you had a nice christmas and a new year eve too :)

**Comment by GiantCrocodile** [comment]
Hey @gi0baro do you know any news if this comes in 0.7?

**Comment by gi0baro** [comment]
Hi @GiantCrocodile, I'm afraid I will re-schedule this again.

I'm really sorry about this, but I want to release 0.7 next week and this issue is big and will need a lot of work, including the complete refactoring of the forms code and the relevant extensions.

Unfortunately in the last months things happened in my personal life and I had no chance to work on weppy as I wanted, things slowed down a bit compared to what I planned.
I think the project would need more developers to evolve with a good rate. But it's not easy to find people that would like to be involved as a core developer on projects like this.

I'm so sorry, I ensure you this will be the first issue I will work on for the 0.8 release.

**Comment by GiantCrocodile** [comment]
Hello @gi0baro, don't feel sorry for your private life. This things happen and nobody is safe from this troubles.

I hope you don't loose time to invest in this project? You are the core developer and your attitude made this framework successful. This is impossible to be replaced. Though I'm not sure why you are not satisfied with the development speed. I still believe in you and your framework and as such I'm sure this "slow" progress is simply faster than you think it is in real. Maybe your opinion changed only because of your current troubles.

Thanks for your information and don't worry about this issue. Any progress is fine and you finished other nice features.

**Comment by gi0baro** [comment]
Works since d8463fe541a7c4cd992e9900656a37bef75b14b9

**Comment by GiantCrocodile** [comment]
Thanks a lot @gi0baro :)!
