### ISSUE TITLE
[Idea] Backend generation with API support

### ISSUE THREAD

**Issue by GiantCrocodile** [gi0baro/weppy#82]
Hey @gi0baro,

I just saw this feature on some frameworks and I really love it. I would like to see weppy to auto-generate backends to edit database fields and entries, based on provided models. Also it would be nice to have some kind of auto-generated JSON-CRUD-API support.

What am I talking about? Look at this links:

http://sailsjs.org/features#?rest
http://sailsjs.org/documentation/reference/blueprint-api

I know that this is a huge request and may not even fit the whole concept or idea. Myself have no clue about how much work this will be nor if it is reasonable/makes sense to implement. This is just what I saw and I enjoyed it a lot while I used sails.js. So I simply suggested it and look forward your opinion!

This may be even 3 ideas in one ticket:
- Backend generation
- JSON API Support
- "Blueprint" support/generation

**Comment by gi0baro** [comment]
Hi @GiantCrocodile, thank you for the good hint.
Regarding the ideas, let me start with a quote from the foreword I've written on the weppy website:

> There are several frameworks that do too much magic behind the scenes

Considering this, I wouldn't add to weppy any feature that *write codes in your place*, first because this is not my idea of web development, but also because I don't believe in the real need of such tools. And this means that I wouldn't add to weppy any command that *magically* write down code for your application because:
- I don't want to have the responsibility of writing parts of *your* application
- Making scaffolds and generating code makes hard for a developer to customize those things for their own applications

Moreover, generating code obey developers to follow a *dictated* development flow, syntax and logic that won't be the best for all the project, and, again, the principle of weppy is that you should focus on *your application*, not the framework itself. If I generate code in applications, you should take time to learn what I did, why I did it, how to customize it, etc.

Given this clarification, I have, instead, planned a couple of extensions in order to provide REST facilities, making easier to write down apis from models, the *main issue* here is the time I have in order to start writing them (also considering that next version has, right now, a high priority since introduces a lot of new features, and 0.7 is important too as it will introduce db indexes and more).
The idea of making REST facilities an extension is driven by the fact that I can't see a good reason to add them to the weppy core, since are interesting only for people writing REST apis.
And, more important, these extension will implement helper classes and methods that should be used by the developer in order to achieve *his* wanted behavior, not another standardized way of *doing that* which is one of the reasons I left other frameworks and started writing weppy.

Concluding, I agree with you that I should write helpers in order to make REST apis development easier with weppy, and I will, simply I don't have an ETA right now :)

Hope this reply will be as robust as I wanted.

**Comment by gi0baro** [comment]
Almost forgot: I won't exclude anyone from writing an extension for weppy that generate code; I would rather enjoy seeing people making extensions! Simply, I won't write something like that :)

**Comment by GiantCrocodile** [comment]
This sounds very right @gi0baro and I agree with you. The magic of other frameworks prevented me to do what I wanted and especially integrating it easily in our project concepts so we were unhappy. Your small feature mentions are enough and the huge one should be skipped/not being done like you said.

Thanks and I appreciate your detailed and dedicated discussions/feedback @gi0baro!
