### ISSUE TITLE
registration feature

### ISSUE THREAD

**Issue by juniverse76** [gi0baro/weppy#85]
Hi, @gi0baro,

I have a question with regarding to Auth module especially related to new user registration.
I want to implement de facto standard way for registration in which a new user is added (perhaps by /account/register), a verification email is sent, then the user confirms the email verification to complete the registration process.
I see there is route for verify_email, but I don't know how I can send email to the new user since the register process is somewhat automated.
So, I guess my questions are following.

1. Is there a way to customize the register process?
2. Do you have any documents about verify_email route? (it seems it's supposed to get extra parameter, but please correct me if i'm wrong)
3. Is there such implementation already exist that i do not know about?

Thank you in advance.

**Comment by gi0baro** [comment]
Hi @juniverse76,
please forgive me if the `Auth` documentation is still incomplete, I will try to explain all the configuration options soon. 

Regarding your questions, the auth module have an option that you can use in order to enable the email verification for registration:

```python
app.config.auth.registration_requires_verification = True
```

and the system will automatically send an email with the verification link to the user. In fact, the auth module rely on the `Mail` class available under `weppy.tools.mail` which you can instantiate and configure:

```python
from weppy.tools.mail import Mail

mailer = Mail(
    app,
    server='smtp.example.com:25',
    sender='you@example.com',
    login='username:password',
    tls=False)

auth = Auth(app, db, usermodel=User, mailer=mailer)
```

Regarding the customization of the registration process, the `Auth` module has two callbacks on registration:

```python
def my_validation(registration_form):
    # code

def my_onaccept(registration_form):
    # code

# set these before auth instance
app.settings.auth.register_onvalidation = [my_validation]
app.settings.auth.register_onaccept = [my_onaccept]
# or these after the auth instance
auth.settings.register_onvalidation = [my_validation]
auth.settings.register_onaccept = [my_onaccept]
```

the `onvalidation` methods will be invoked during form validation, and the `onaccept` will be invoked after the form has passed the validation and user was registered, just before the redirection.

Let me know if you need more.

**Comment by juniverse76** [comment]
@gi0baro, thank you for your reply.

I knew there would be such feature, and I'm sure you are too busy to keep up with the documents.
With your insight provided above, I was able to trace your code better to find additional features I needed.
Well, thank you again for your hard work!
